version: '3'
services:
  mysql:
    build:
      context: ./db
    env_file:
      - ./.env
    container_name: posture-correction-mysql
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 4202:3306
    networks:
      - posture-correction
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: ./.env
    container_name: posture-correction-phpmyadmin
    ports:
      - 4203:80
    depends_on:
      - mysql
    networks:
      - posture-correction

  api:
    build: 
      context: ./
      dockerfile: api/Dockerfile
    env_file:
      - ./.env
    container_name: posture-correction-api
    volumes:
      - ./api/.venv:/app/.venv
      - ./api/__pycache__:/app/__pycache__
      - ./api:/app
    ports:
      - 4201:8000
    depends_on:
      - mysql
    tty: true
    networks:
      - posture-correction

  client:
    build: 
      context: ./
      dockerfile: client/Dockerfile
    env_file:
      - ./.env
    container_name: posture-correction-client
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
      - ./client/src/proxy.conf.json:/app/src/proxy.conf.json
    depends_on:
      - mysql
    tty: true
    networks:
      - posture-correction

volumes:
  mysql:
  node_modules:
  .venv:

networks:
  posture-correction:
    driver: bridge