version: '3'
services:
  mysql:
    build:
      context: ./db
    env_file:
      - ./.env
    container_name: posture-collection-mysql
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 4202:3306
    cap_add:
      - SYS_NICE
    networks:
      - posture-collection
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: ./.env
    container_name: posture-collection-phpmyadmin
    ports:
      - 4203:80
    depends_on:
      - mysql
    networks:
      - posture-collection

  api:
    build: 
      context: ./
      dockerfile: api/Dockerfile
    env_file:
      - ./.env
    container_name: posture-collection-api
    volumes:
      - .venv:/app/.venv
      - ./api/__pycache__:/app/__pycache__
      - ./api:/app
    ports:
      - 4201:8000
    depends_on:
      - mysql
    tty: true
    networks:
      - posture-collection

  client:
    build: 
      context: ./
      dockerfile: client/Dockerfile
    env_file:
      - ./.env
    container_name: posture-collection-client
    ports:
      - 4200:4200
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
      - environments:/app/src/environments
      - proxy_config:/app/src/proxy_config
    depends_on:
      - mysql
    tty: true
    networks:
      - posture-collection

volumes:
  mysql:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/client/node_modules
      o: bind
  environments:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/client/src/environments
      o: bind
  proxy_config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/client/src/proxy_config
      o: bind
  .venv:

networks:
  posture-collection:
    driver: bridge